In [4]:
from sklearn import cluster
import numpy as np

C:\Users\mseok\user\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [5]:
import pandas as pd

C:\Users\mseok\user\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [6]:
# 데이터를 불러옵니다.
pixels_data = pd.read_csv('./fer2013/fer2013.csv')
pixels_data.head()

emotion                                             pixels     Usage
0        0  70 80 82 72 58 58 60 63 54 58 60 48 89 115 121...  Training
1        0  151 150 147 155 148 133 111 140 170 174 182 15...  Training
2        2  231 212 156 164 174 138 161 173 182 200 106 38...  Training
3        4  24 32 36 30 32 23 19 20 30 41 21 22 32 34 21 1...  Training
4        6  4 0 0 0 0 0 0 0 0 0 0 0 3 15 23 28 48 50 58 84...  Training

In [7]:
# 필요없는 열을 제거합니다.
del pixels_data['Usage']

In [8]:
pixels_data.head()

emotion                                             pixels
0        0  70 80 82 72 58 58 60 63 54 58 60 48 89 115 121...
1        0  151 150 147 155 148 133 111 140 170 174 182 15...
2        2  231 212 156 164 174 138 161 173 182 200 106 38...
3        4  24 32 36 30 32 23 19 20 30 41 21 22 32 34 21 1...
4        6  4 0 0 0 0 0 0 0 0 0 0 0 3 15 23 28 48 50 58 84...

In [9]:
# emotion이라는 열을 따로 만들어줍니다.
emotion = pixels_data[['emotion']].copy()
emotion.head()

emotion
0        0
1        0
2        2
3        4
4        6

In [10]:
del pixels_data['emotion']
pixels_data.head()

pixels
0  70 80 82 72 58 58 60 63 54 58 60 48 89 115 121...
1  151 150 147 155 148 133 111 140 170 174 182 15...
2  231 212 156 164 174 138 161 173 182 200 106 38...
3  24 32 36 30 32 23 19 20 30 41 21 22 32 34 21 1...
4  4 0 0 0 0 0 0 0 0 0 0 0 3 15 23 28 48 50 58 84...

In [11]:
from sklearn import model_selection

In [12]:
# model_selection을 통해 train / test로 무작위적으로 나눕니다.
train_data, test_data, train_label, test_label = model_selection.train_test_split(pixels_data, emotion, test_size=0.3, random_state=0)

In [13]:
import numpy as np

In [14]:
# pixels를 2304개의 열로 split합니다.
train_data = np.array(list(map(str.split, train_data.pixels)), np.float32) 
test_data = np.array(list(map(str.split, test_data.pixels)), np.float32) 

In [15]:
# train_data의 Max 값이 255로 나누어 0 ~ 1 사이의 숫자들로 만들어줍니다.
train_data = train_data / 255.0
test_data = test_data / 255.0

In [16]:
X = np.array(train_data)
X

array([[0.01176471, 0.00784314, 0.00784314, ..., 0.36862746, 0.4       ,
        0.42745098],
       [0.7921569 , 0.7764706 , 0.7411765 , ..., 0.6901961 , 0.68235296,
        0.69803923],
       [1.        , 1.        , 1.        , ..., 0.49411765, 0.45490196,
        0.4509804 ],
       ...,
       [0.23529412, 0.23921569, 0.2509804 , ..., 0.23921569, 0.22745098,
        0.25490198],
       [0.43137255, 0.49019608, 0.52156866, ..., 0.5921569 , 0.61960787,
        0.654902  ],
       [0.10588235, 0.11764706, 0.12941177, ..., 0.9647059 , 0.29803923,
        0.        ]], dtype=float32)

In [17]:
from sklearn import cluster

In [18]:
# cluster 라이브러리의 KMeans의 클러스터 개수를 7개로 해줍니다.
kmeans = cluster.KMeans(n_clusters=7, random_state=0).fit(X)
kmeans

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=7, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=0, tol=0.0001, verbose=0)

In [19]:
print("Clusters : ", kmeans.labels_)

Clusters :  [2 0 3 ... 4 6 0]


In [20]:
# ???
print("Cluster centroids: ", kmeans.cluster_centers_)

Cluster centroids:  [[0.37982002 0.37326518 0.36301947 ... 0.45603442 0.45813006 0.45999914]
 [0.5788802  0.576124   0.5719404  ... 0.3645118  0.37184328 0.37813807]
 [0.27553308 0.2673473  0.25875515 ... 0.24402152 0.2467265  0.2514339 ]
 ...
 [0.43751532 0.42563003 0.41522506 ... 0.42548966 0.42620596 0.42915717]
 [0.28400677 0.26699987 0.2515396  ... 0.26888067 0.26958454 0.27365327]
 [0.59119326 0.56979036 0.54863673 ... 0.6584321  0.6613525  0.662688  ]]


In [21]:
# test_data 안의 pixels를 예측해봅니다.
print("Prediction cluster of test_data: ", kmeans.predict(np.array(test_data)))

Prediction cluster of test_data:  [3 5 3 ... 5 1 5]


In [22]:
from sklearn import metrics

In [27]:
# Accuracy를 측정해봅니다.
score = metrics.accuracy_score(test_label, kmeans.predict(test_data))
print('Accuracy : {0:f}'.format(score))

Accuracy : 0.122968
